# generated by datamodel-codegen:
#   filename:  schema.yaml
#   timestamp: 2025-08-07T14:40:44+00:00

from __future__ import annotations
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, Field


class Version(Enum):
    v1 = "v1"


class Prompt(BaseModel):
    name: Optional[str] = Field(None, description="Prompt name")
    prompt: str = Field(..., description="Prompt text")
    description: Optional[str] = None


class Dataset(BaseModel):
    name: str = Field(..., description="Dataset name")
    rag_strategy: Optional[str] = Field("auto", description="RAG strategy to use for the dataset")
    files: list[str] = Field(..., description="List of file hashes")


class Provider(Enum):
    openai = "openai"
    anthropic = "anthropic"
    google = "google"
    local = "local"
    custom = "custom"


class Model(BaseModel):
    provider: Provider
    model: str = Field(..., description="Model name or ID")


class LlamaFarmConfig(BaseModel):
    version: Version = Field(..., description='Config version, must be "v1"')
    name: str = Field(..., description="Project name", example="my-namespace/my-project")
    prompts: list[Prompt]
    rag: dict[str, Any]
    datasets: list[Dataset] = Field(..., description="List of dataset configurations")
    models: list[Model] = Field(..., description="List of model configurations")
